### ISSUE TITLE
Authentik error on deploy

### ISSUE THREAD

**Issue by bannert1337** [Lissy93/portainer-templates#38]
When I try to deploy an Authentik stack from App Templates, I get this error:
```
Deployment error
failed to deploy a stack: parsing /data/compose/15/51e04cdd91cdec9e3e926519fa1b2914fe7902d9/Template/Stack/authentik.yml: error while interpolating services.postgresql.environment.[]: required variable PG_PASS is missing a value: database password required
```

**Comment by EnchantedAirApp** [comment]
@il I byit

**Comment by Lissy93** [comment]
See: https://github.com/Lissy93/portainer-templates?tab=readme-ov-file#raising-issues

Issues relating to specific images need to be raised upstream.

This repo just collates templates listed in the [Sources](https://github.com/Lissy93/portainer-templates?tab=readme-ov-file#sources) into a single manifest, so once a fix has been pushed out upstream, it will be available here.

**Comment by Altirix** [comment]
fyi the upstream that this config is pulled from has issues disabled https://github.com/xneo1/portainer_templates/blob/master/Template/Stack/authentik.yml

the issue @bannert1337 is having is due to some missing env variables. you'll need to copy the template as a custom and modify it to use stack.env and add in these
```
PG_PASS
AUTHENTIK_PORT_HTTP
AUTHENTIK_PORT_HTTPS
```

granted that template is 2 years old, at that point you are better off pulling the docker-compose from authentik and modifying it (the env variables changed btw).

also if you are using docker rootless youll run into issues with the mounted folders
